server:
  port: 8081

spring:
  application:
    name: auth-service

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: when-authorized

app:
  cors:
    allowed-origins: ${APP_CORS_ALLOWED_ORIGINS:http://localhost:4200}

#keycloak:
#  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8091}
#  realm: ${KEYCLOAK_REALM:my-realm}
#  # Client used by auth-service for password/refresh grants (frontend-facing client)
#  client-id: ${KEYCLOAK_CLIENT_ID:auth-service}
#  client-secret: ${KEYCLOAK_CLIENT_SECRET:change-me}
#  # Service-account client used for Admin API calls (client_credentials)
#  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:auth-service-admin}
#  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:change-me}

keycloak:
  base-url: ${KEYCLOAK_BASE_URL:http://localhost:8091}
  realm: ${KEYCLOAK_REALM:my-realm}
  client-id: ${KEYCLOAK_CLIENT_ID:auth-service}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:}
  admin-client-id: ${KEYCLOAK_ADMIN_CLIENT_ID:auth-service-admin}
  admin-client-secret: ${KEYCLOAK_ADMIN_CLIENT_SECRET:}
