server.port=8081
spring.application.name=auth-service

app.cors.allowed-origins=http://localhost:5173,http://localhost:4200
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3360/pfedb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:pfeuser}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8091/realms/my-realm