sonar.projectName=PFEPROJECT
sonar.sourceEncoding=UTF-8

sonar.sources=Backend/src/main/java,FrontEndF/src/app,PFERTC/ml/src,PFERTC/scripts
sonar.tests=Backend/src/test/java
sonar.java.binaries=Backend/target/classes
sonar.java.test.binaries=Backend/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=Backend/target/site/jacoco/jacoco.xml

sonar.exclusions=**/node_modules/**,**/dist/**,**/target/**,**/artifacts/**,FrontEndF/velson_template/**,Backend/src/main/resources/manual-sql/**,**/*.spec.ts,**/*.spec.html
sonar.coverage.exclusions=PFERTC/**,FrontEndF/src/**/*.spec.ts,FrontEndF/src/**/*.spec.html
sonar.python.version=3.11
