@startuml
left to right direction
actor "Utilisateur (non authentifié)" as user

rectangle "Sous-système d'authentification" {
  usecase "S'authentifier" as UC_Auth
  usecase "Réinitialiser le mot de passe" as UC_Reset
  usecase "Se déconnecter" as UC_Logout
}

user --> UC_Auth
user --> UC_Reset
user --> UC_Logout
@enduml