ALTER TABLE camera_list
    ADD COLUMN IF NOT EXISTS name VARCHAR(128) NULL,
    ADD COLUMN IF NOT EXISTS site VARCHAR(128) NULL,
    ADD COLUMN IF NOT EXISTS type VARCHAR(64) NULL,
    ADD COLUMN IF NOT EXISTS created_at DATETIME NULL,
    ADD COLUMN IF NOT EXISTS updated_at DATETIME NULL;
