apiVersion: v1
kind: Secret
metadata:
  name: pfe-postgres-secret
  namespace: pfeworks
type: Opaque
stringData:
  POSTGRES_DB: monotoring
  POSTGRES_USER: pfeuser
  POSTGRES_PASSWORD: pg14789
---
apiVersion: v1
kind: Secret
metadata:
  name: pfe-keycloak-mysql-secret
  namespace: pfeworks
type: Opaque
stringData:
  MYSQL_DATABASE: keycloak
  MYSQL_USER: pfeuser
  MYSQL_PASSWORD: pfepassword
  MYSQL_ROOT_PASSWORD: rootpassword
---
apiVersion: v1
kind: Secret
metadata:
  name: pfe-keycloak-app-secret
  namespace: pfeworks
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  KEYCLOAK_AUTH_CLIENT_SECRET: change-me-auth-service-secret
  KEYCLOAK_ADMIN_CLIENT_SECRET: change-me-auth-service-admin-secret
